package com.bist.homework.todolist.entity;

import lombok.*;

import javax.persistence.*;
import java.util.Date;

@Entity
//Entity : JPA : DB Object
@Table(name = "items")
//Table : JPA : Define table for adding
@Data
@NoArgsConstructor
//NoArgsConstructor : Lombok : Creates no arguments constructor
@AllArgsConstructor
//AllArgsConstructor : Lombok : Creates all arguments constructor
@ToString
//ToString : Lombok : Creates toString method
@EqualsAndHashCode
//EqualsAndHashCode : Lombok : Creates equals and hashcode methods, maybe usefull for future
/**
 * DB Object. When new item arrives, it will be added into items table in database.
 * id : item id, a unique Long number auto generated by system
 * name : item name
 * date : due date
 * checked : this is for checkbox in FE
 */
public class Item extends BaseEntity{
    @Id
    //Id : JPA : Primary key definition.
    @GeneratedValue(strategy = GenerationType.AUTO)
    //GeneratedValue : JPA : auto generated number by database. GenerationType may be not support in spesific databse.
    private Long id;

    @Column(name = "item_name",length = 30, unique = true)
    //Column : JPA : DB properties, name for column name
    private String name;

    @Column(name = "due_date")
    @Temporal(TemporalType.DATE)
    //Temporal : JPA : Define Date type
    private Date date;

    @Column(name = "is_checked")
    private Boolean checked;

}
